name: .NET Desktop Build (EXE/DLL Release)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]  # Only build Release (no Debug needed for releases)
    runs-on: windows-latest

    env:
      Solution_Name: JDMyFiles.sln
      Project_Path: JD.PhotoDuplicates\JD.PhotoDuplicates.csproj  # Your main project
      Output_Dir: bin\Release\net8.0-windows  # .NET 8 Windows output folder

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore and Build
        run: |
          dotnet restore $env:Solution_Name
          dotnet build $env:Project_Path --configuration ${{ matrix.configuration }} --no-restore

      - name: Zip Binaries
        run: |
          $outputPath = "$env:Project_Path\..\$env:Output_Dir"
          $zipName = "JD.PhotoDuplicates_${{ github.run_number }}.zip"
          Compress-Archive -Path "$outputPath\*" -DestinationPath $zipName -Force
          echo "ZIP_PATH=$zipName" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Upload Release ZIP
        uses: actions/upload-artifact@v4
        with:
          name: JD.PhotoDuplicates_${{ matrix.configuration }}
          path: ${{ env.ZIP_PATH }}